spring:
  #thymeleaf配置
  thymeleaf:
    cache: false
  #mysql配置
  datasource:
    url: jdbc:mysql://localhost:3306/day84
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
